// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/changes": {
            "get": {
                "description": "根据站点ID和变化类型查询历史变化",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "变化记录"
                ],
                "summary": "查询变化记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "站点ID",
                        "name": "site_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "变化类型 (js 或 content)",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ChangeRecord"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/content": {
            "get": {
                "description": "根据站点ID、文件路径或哈希值查询历史文件内容",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "内容快照"
                ],
                "summary": "获取文件内容快照",
                "parameters": [
                    {
                        "type": "string",
                        "description": "站点ID",
                        "name": "site_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件路径",
                        "name": "file_path",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "内容哈希值(MD5)",
                        "name": "hash",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.FileContent"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/site-hooks": {
            "get": {
                "description": "返回指定站点所有启用的 Hook 脚本（用于客户端注入）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hook脚本"
                ],
                "summary": "获取站点 Hook 脚本",
                "parameters": [
                    {
                        "type": "string",
                        "description": "站点完整URL",
                        "name": "url",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SiteHooksResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/sites": {
            "get": {
                "description": "返回所有被监控的站点列表，支持分页",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "站点管理"
                ],
                "summary": "获取所有站点",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "每页数量，默认20，最大100",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.SitesPageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "监控工具上传检测到的JS或内容变化",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "变化记录"
                ],
                "summary": "上传变化记录",
                "parameters": [
                    {
                        "description": "上传数据",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UploadChangeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ChangeRecord": {
            "type": "object",
            "properties": {
                "change_diff": {
                    "type": "string"
                },
                "change_type": {
                    "type": "string"
                },
                "detected_at": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "site_id": {
                    "type": "string"
                },
                "snapshot_hash": {
                    "type": "string"
                }
            }
        },
        "models.FileContent": {
            "type": "object",
            "properties": {
                "change_record_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "content_hash": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "site_id": {
                    "type": "string"
                }
            }
        },
        "models.MonitoredSite": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "models.SiteHooksResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "content": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.SitesPageResponse": {
            "type": "object",
            "properties": {
                "page": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页数量",
                    "type": "integer"
                },
                "sites": {
                    "description": "站点列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MonitoredSite"
                    }
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                }
            }
        },
        "models.UploadChangeRequest": {
            "type": "object",
            "required": [
                "change_diff",
                "change_type",
                "site_url",
                "snapshot_hash"
            ],
            "properties": {
                "change_diff": {
                    "type": "string"
                },
                "change_type": {
                    "type": "string",
                    "enum": [
                        "js",
                        "content"
                    ]
                },
                "content": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "site_name": {
                    "type": "string"
                },
                "site_url": {
                    "type": "string"
                },
                "snapshot_hash": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "站点监控服务 API",
	Description:      "用于接收监控工具上报的变化数据，并提供站点 Hook 脚本配置。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
